# Adapted from vercel/next.js
name: Issue Stale
on:
  workflow_dispatch:
  schedule:
    # This runs every day 20 minutes before midnight: https://crontab.guru/#40_23_*_*_*
    - cron: "40 23 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'shadcn-ui'
    steps:
      - uses: actions/stale@v4
        id: stale-no-repro
        name: "Close stale issues with no reproduction"
        with:
          repo-token: ${{ secrets.STALE_TOKEN }}
          close-issue-message: "This issue has been automatically closed because it received no activity for a while. If you think it was closed by accident, please leave a comment. Thank you."
          days-before-issue-close: 7
          days-before-issue-stale: 15
          stale-pr-label: "stale?"
          days-before-pr-close: -1
          days-before-pr-stale: -1
          exempt-issue-labels: "roadmap,next,bug"
          operations-per-run: 300 # 1 operation per 100 issues, the rest is to label/comment/close
